version: '3'

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service:alpine
    build: .
    volumes:
      - ./logs/text.log:/usr/src/app/text.log
    container_name: simple-web-service2.1