version: '3'

services:
  frontend:
    ports:
      - 5000:5000
    build:
      context: ../../material-applications/example-frontend
      dockerfile: ../../Part02/2.10/dockerfiles/frontend/Dockerfile
    container_name: frontend2.8
  
  backend:
    ports:
      - 8080:8080
    build:
      context: ../../material-applications/example-backend
      dockerfile: ../../Part02/2.10/dockerfiles/backend/Dockerfile
    environment:
      - REDIS_HOST=redisdbcache
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: backend2.8
  
  redisdbcache:
    image: redis:6.0
    ports:
      - 6379:6379
    container_name: redisdbcache2.8
    
  db:
    image: postgres:14.1-bullseye
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    container_name: postgresdb2.8

  nginx:
    ports:
      - 80:80
    image: nginx:1.21.4-alpine
    restart: always
    depends_on:
      - frontend
      - backend
      - redisdbcache
      - db
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx2.8